/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package EasyShop.front_end;

import EasyShop.util.OrderData;
import com.google.firebase.database.DataSnapshot;
import com.google.firebase.database.DatabaseError;
import com.google.firebase.database.DatabaseReference;
import com.google.firebase.database.FirebaseDatabase;
import com.google.firebase.database.ValueEventListener;
import com.google.firebase.messaging.FirebaseMessaging;
import com.google.firebase.messaging.Message;
import com.google.firebase.messaging.Notification;
import java.awt.CardLayout;
import java.awt.Color;
import java.util.LinkedList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kaka
 */
public class Iuy34asjkh extends javax.swing.JFrame {
    private LinkedList<OrderData> q12q = new LinkedList<OrderData>();
    private CardLayout cardlayout;
    private OrderData aqfr;
    private hjklout678 p;
    int xMouse = 0;
    int yMouse = 0;
    /**
     * Creates new form OrderSearch
     */
    public Iuy34asjkh(LinkedList<OrderData> od ,  hjklout678 pn) {
        p =pn;
        this.setUndecorated(true);
        initComponents();
        this.setLocationRelativeTo(this);
        this.q12q = od;
        jdghsk.setIcon(new ImageIcon("bin/icon_search.png"));
        notfound_icon.setIcon(new ImageIcon("bin/notfound.png"));
        cardlayout = (CardLayout) this.jskdf34.getLayout();
        cardlayout.show(jskdf34, "empty");
    }
    public Iuy34asjkh() {
        this.setUndecorated(true);
        initComponents();
        this.setLocationRelativeTo(null);
        cardlayout = (CardLayout) this.jskdf34.getLayout();
        cardlayout.show(jskdf34, "empty");
        
    }
    
    private void Search(){
        boolean f =false;
        try{
            String query = this.dkjlfhu34.getText();
            for (OrderData o : q12q) {
                String id = o.getOrderId();
                if(query.toLowerCase().equals(id.toLowerCase())){
                    aqfr = o;
                    f = true;
                    break;
                }
            }
            if(f){
                
                cardlayout.show(this.jskdf34, "found");
                DefaultTableModel model = (DefaultTableModel) FDE.getModel();
                model.setRowCount(0);
                AD.setText(aqfr.getOrderP());
                Object[] r = {aqfr.productname, aqfr.quantity, aqfr.price};
                model.addRow(r);
                for (OrderData nextOrder : aqfr.nextOrders) {
                    Object[] row = {nextOrder.productname, nextOrder.quantity, nextOrder.price};
                    model.addRow(row);
                }
            }else{
                cardlayout.show(this.jskdf34, "notfound");
            }
        }catch(NullPointerException e){
            System.out.println(e.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dfjlk23kjs = new javax.swing.JPanel();
        dkjlfhu34 = new javax.swing.JTextField();
        jdghsk = new javax.swing.JLabel();
        dfkj23 = new javax.swing.JPanel();
        x = new javax.swing.JLabel();
        jskdf34 = new javax.swing.JPanel();
        dkjsf43 = new javax.swing.JPanel();
        idsr34 = new javax.swing.JPanel();
        HKA3j = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        FDE = new javax.swing.JTable();
        AD = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        sieruiw = new javax.swing.JPanel();
        notfound_icon = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        dfjlk23kjs.setBackground(new java.awt.Color(255, 255, 255));
        dfjlk23kjs.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        dkjlfhu34.setForeground(new java.awt.Color(153, 153, 153));
        dkjlfhu34.setText("Search");
        dkjlfhu34.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 153)));
        dkjlfhu34.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dkjlfhu34MouseClicked(evt);
            }
        });
        dkjlfhu34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dkjlfhu34ActionPerformed(evt);
            }
        });
        dkjlfhu34.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dkjlfhu34KeyPressed(evt);
            }
        });

        jdghsk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jdghskMouseClicked(evt);
            }
        });

        dfkj23.setBackground(new java.awt.Color(51, 51, 51));
        dfkj23.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                dfkj23MouseDragged(evt);
            }
        });
        dfkj23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dfkj23MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dfkj23MousePressed(evt);
            }
        });

        x.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        x.setForeground(new java.awt.Color(255, 255, 255));
        x.setText("X");
        x.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                xMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                xMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                xMouseExited(evt);
            }
        });

        javax.swing.GroupLayout dfkj23Layout = new javax.swing.GroupLayout(dfkj23);
        dfkj23.setLayout(dfkj23Layout);
        dfkj23Layout.setHorizontalGroup(
            dfkj23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dfkj23Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(x)
                .addContainerGap())
        );
        dfkj23Layout.setVerticalGroup(
            dfkj23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dfkj23Layout.createSequentialGroup()
                .addComponent(x)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jskdf34.setLayout(new java.awt.CardLayout());

        dkjsf43.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout dkjsf43Layout = new javax.swing.GroupLayout(dkjsf43);
        dkjsf43.setLayout(dkjsf43Layout);
        dkjsf43Layout.setHorizontalGroup(
            dkjsf43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 455, Short.MAX_VALUE)
        );
        dkjsf43Layout.setVerticalGroup(
            dkjsf43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 254, Short.MAX_VALUE)
        );

        jskdf34.add(dkjsf43, "empty");

        idsr34.setBackground(new java.awt.Color(255, 255, 255));

        HKA3j.setText("Mark as Done");
        HKA3j.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HKA3jMouseClicked(evt);
            }
        });
        HKA3j.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HKA3jActionPerformed(evt);
            }
        });

        FDE.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        FDE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Product Name", "Quantity", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        FDE.setRowHeight(22);
        jScrollPane1.setViewportView(FDE);

        AD.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        AD.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(204, 204, 204)));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Total");

        javax.swing.GroupLayout idsr34Layout = new javax.swing.GroupLayout(idsr34);
        idsr34.setLayout(idsr34Layout);
        idsr34Layout.setHorizontalGroup(
            idsr34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(idsr34Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(HKA3j, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
                .addGap(55, 55, 55))
            .addGroup(idsr34Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, idsr34Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(AD, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        idsr34Layout.setVerticalGroup(
            idsr34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, idsr34Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(idsr34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(idsr34Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(HKA3j))
        );

        jskdf34.add(idsr34, "found");

        sieruiw.setBackground(new java.awt.Color(255, 255, 255));

        notfound_icon.setText("jLabel3");

        jLabel5.setBackground(new java.awt.Color(255, 51, 51));
        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 51, 51));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Order Not found");

        javax.swing.GroupLayout sieruiwLayout = new javax.swing.GroupLayout(sieruiw);
        sieruiw.setLayout(sieruiwLayout);
        sieruiwLayout.setHorizontalGroup(
            sieruiwLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sieruiwLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(sieruiwLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(notfound_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(sieruiwLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(193, Short.MAX_VALUE))
        );
        sieruiwLayout.setVerticalGroup(
            sieruiwLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sieruiwLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(notfound_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jskdf34.add(sieruiw, "notfound");

        javax.swing.GroupLayout dfjlk23kjsLayout = new javax.swing.GroupLayout(dfjlk23kjs);
        dfjlk23kjs.setLayout(dfjlk23kjsLayout);
        dfjlk23kjsLayout.setHorizontalGroup(
            dfjlk23kjsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dfkj23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(dfjlk23kjsLayout.createSequentialGroup()
                .addGroup(dfjlk23kjsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dfjlk23kjsLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(dkjlfhu34, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jdghsk))
                    .addGroup(dfjlk23kjsLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jskdf34, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        dfjlk23kjsLayout.setVerticalGroup(
            dfjlk23kjsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dfjlk23kjsLayout.createSequentialGroup()
                .addComponent(dfkj23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(dfjlk23kjsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dkjlfhu34, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jdghsk, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jskdf34, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dfjlk23kjs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dfjlk23kjs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dkjlfhu34MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dkjlfhu34MouseClicked
        // TODO add your handling code here:
        cardlayout.show(jskdf34, "empty");
        if(dkjlfhu34.getText().trim().toLowerCase().equals("search")){
            dkjlfhu34.setText("");
        }
             
    }//GEN-LAST:event_dkjlfhu34MouseClicked

    private void jdghskMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jdghskMouseClicked
        // TODO add your handling code here:
        Search();
    }//GEN-LAST:event_jdghskMouseClicked

    private void xMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xMouseEntered
        // TODO add your handling code here:
        this.x.setForeground(Color.red);
    }//GEN-LAST:event_xMouseEntered

    private void xMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xMouseExited
        // TODO add your handling code here:
        this.x.setForeground(Color.WHITE);
    }//GEN-LAST:event_xMouseExited

    private void xMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_xMouseClicked

    private void HKA3jMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HKA3jMouseClicked
        // TODO add your handling code here:
        DatabaseReference reforder = FirebaseDatabase.getInstance().getReference("Order/"+aqfr.shopid+"/Products");
        DatabaseReference refrider = FirebaseDatabase.getInstance().getReference("OrderBiker/");
        reforder.addListenerForSingleValueEvent(new ValueEventListener() {
            @Override
            public void onDataChange(DataSnapshot ds) {
                for(int i =0;i<aqfr.orderIDs.size(); i++){
                    refrider.child(aqfr.shopid+"/Products/"+aqfr.orderIDs.get(i)).setValueAsync(ds.child(aqfr.orderIDs.get(i)).getValue());
                    reforder.child(aqfr.orderIDs.get(i)+"/ordercomplete").setValueAsync("1");
                    ju887(i,reforder,aqfr);
                }
                int index = q12q.indexOf(aqfr);
                q12q.remove(index);
                p.reDraw();
                JOptionPane.showMessageDialog(null, "Moved to rider");
                exit();
            }

            @Override
            public void onCancelled(DatabaseError de) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        });
   
    }//GEN-LAST:event_HKA3jMouseClicked


    
    private void exit(){
//        gio908();
        this.dispose();
    }
    private void HKA3jActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HKA3jActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HKA3jActionPerformed
    
    private void ju887(int val, DatabaseReference reforder,OrderData o ){
        DatabaseReference refBiker = FirebaseDatabase.getInstance().getReference("Biker/");
        refBiker.orderByChild("shopId").equalTo(o.shopid)
                            .limitToFirst(1).addListenerForSingleValueEvent(new ValueEventListener() {
                        @Override
                        public void onDataChange(DataSnapshot ds) {
                            for (DataSnapshot d : ds.getChildren()) {
                                reforder.child(o.orderIDs.get(val)+"/bikeplate").setValueAsync(d.child("bikeNumber").getValue().toString());
                                reforder.child(o.orderIDs.get(val)+"/bikerphn").setValueAsync(d.child("phone").getValue().toString());
                                try {
                                    Message m = Message.builder()
                                            .putData("New Order placed", "")
                                            .setNotification(new Notification("New Order Placed",
                                                    "Please reach your shop."))
                                            .setTopic(d.child("subscriptionid").getValue().toString())
                                            .build();
                                    String response = FirebaseMessaging.getInstance().send(m);

                                } catch (Exception ex) {
                                    ex.printStackTrace();
                                }
                                break;
                            }
                            
                        }

                        @Override
                        public void onCancelled(DatabaseError de) {
                            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                        }
                    });
    }   
    
    private void dkjlfhu34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dkjlfhu34ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dkjlfhu34ActionPerformed

    private void dkjlfhu34KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dkjlfhu34KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == 10){
            Search();
        }
    }//GEN-LAST:event_dkjlfhu34KeyPressed

    private void dfkj23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dfkj23MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_dfkj23MouseClicked

    private void dfkj23MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dfkj23MouseDragged
        // TODO add your handling code here:
        int xd = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(xd-xMouse, y-yMouse);
    }//GEN-LAST:event_dfkj23MouseDragged

    private void dfkj23MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dfkj23MousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_dfkj23MousePressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AD;
    private javax.swing.JTable FDE;
    private javax.swing.JButton HKA3j;
    private javax.swing.JPanel dfjlk23kjs;
    private javax.swing.JPanel dfkj23;
    private javax.swing.JTextField dkjlfhu34;
    private javax.swing.JPanel dkjsf43;
    private javax.swing.JPanel idsr34;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jdghsk;
    private javax.swing.JPanel jskdf34;
    private javax.swing.JLabel notfound_icon;
    private javax.swing.JPanel sieruiw;
    private javax.swing.JLabel x;
    // End of variables declaration//GEN-END:variables
}
