/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package EasyShop.front_end;

import com.google.firebase.database.DataSnapshot;
import com.google.firebase.database.DatabaseError;
import com.google.firebase.database.DatabaseReference;
import com.google.firebase.database.FirebaseDatabase;
import com.google.firebase.database.ValueEventListener;
import java.awt.Color;
import java.util.LinkedList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kaka
 */
public class sdfkh32 extends javax.swing.JFrame {
    private class pdata{
        String name;
        String barcode;
        String quant;
        String sp;
        String pp;
        String shopid;

        public pdata(String name, String barcode, String quant, String sp, String pp, String shopid) {
            this.name = name;
            this.barcode = barcode;
            this.quant = quant;
            this.sp = sp;
            this.pp = pp;
            this.shopid = shopid;
        }
        
    }
    
    private LinkedList<pdata> list = new LinkedList<>(); 
    private int index =1;
    private int xMouse =0;
    private int yMouse =0;
    /**
     * Creates new form searchProducts
     */
    public sdfkh32() {
        this.setUndecorated(true);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dfkjsh12 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        sdfjh234nm = new javax.swing.JComboBox<>();
        djskfh123 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        hsad123rte = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        dfkjsh12.setBackground(new java.awt.Color(255, 255, 255));
        dfkjsh12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("X");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        sdfjh234nm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "name", "barcode" }));
        sdfjh234nm.setBorder(null);
        sdfjh234nm.setRequestFocusEnabled(false);

        djskfh123.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        djskfh123.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 153)));
        djskfh123.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                djskfh123MouseClicked(evt);
            }
        });
        djskfh123.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                djskfh123ActionPerformed(evt);
            }
        });
        djskfh123.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                djskfh123KeyPressed(evt);
            }
        });

        hsad123rte.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        hsad123rte.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "", ""
            }
        ));
        hsad123rte.setRowHeight(20);
        jScrollPane1.setViewportView(hsad123rte);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Product Search");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Product Details");

        javax.swing.GroupLayout dfkjsh12Layout = new javax.swing.GroupLayout(dfkjsh12);
        dfkjsh12.setLayout(dfkjsh12Layout);
        dfkjsh12Layout.setHorizontalGroup(
            dfkjsh12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(dfkjsh12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(378, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dfkjsh12Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(dfkjsh12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(dfkjsh12Layout.createSequentialGroup()
                        .addComponent(sdfjh234nm, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(djskfh123, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3))
                .addGap(41, 41, 41))
        );
        dfkjsh12Layout.setVerticalGroup(
            dfkjsh12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dfkjsh12Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addGroup(dfkjsh12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sdfjh234nm, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(djskfh123, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dfkjsh12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(dfkjsh12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @SuppressWarnings("empty-statement")
    private void updateview(pdata d){ 
        DefaultTableModel model = (DefaultTableModel) hsad123rte.getModel();
        model.setRowCount(0);        
        Object[] row0 = {"name",d.name}; 
        model.addRow(row0);
        Object[] row1 = {"barcode", d.barcode};
        model.addRow(row1);
        Object[] row2 = {"Purchase Price", d.pp};
        model.addRow(row2);
        Object[] row3 = {"Sales Price", d.sp};
        model.addRow(row3);
        Object[] row4 = {"quantity", d.quant};
        model.addRow(row4);
        Object[] row5 = {"Shop ID", d.shopid};
        model.addRow(row5);
    }
    
    private void djskfh123KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_djskfh123KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == 10){
            DatabaseReference ref = FirebaseDatabase.getInstance().getReference("ProductsItems");
            ref.orderByChild(sdfjh234nm.getSelectedItem().toString()).equalTo(djskfh123.getText()).addListenerForSingleValueEvent(new ValueEventListener() {
                @Override
                public void onDataChange(DataSnapshot ds) {
                    list.clear();
                    if(ds.getChildrenCount() >0){
                        for (DataSnapshot d : ds.getChildren()) {
                            String name = d.child("name").getValue().toString();
                            String barcode = d.child("barcode").getValue().toString();
                            String q = d.child("quantity").getValue().toString();
                            String sp = d.child("salesprice").getValue().toString();
                            String pp = d.child("price").getValue().toString();
                            String sh = d.child("shop_id").getValue().toString();
                            list.add(new pdata(name, barcode, q, sp, pp, sh));
                            
                        }
                        updateview(list.get(0));
                    }else{
                        JOptionPane.showMessageDialog(null , "No Product Found" );
                    }
                }

                @Override
                public void onCancelled(DatabaseError de) {
                    throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                }
            }); 
        }
    }//GEN-LAST:event_djskfh123KeyPressed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        // TODO add your handling code here:
        jLabel2.setForeground(Color.red);
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
        // TODO add your handling code here:
        jLabel2.setForeground(Color.white);
    }//GEN-LAST:event_jLabel2MouseExited

    private void djskfh123ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_djskfh123ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_djskfh123ActionPerformed

    private void djskfh123MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_djskfh123MouseClicked
        // TODO add your handling code here:
        djskfh123.setText("");
        DefaultTableModel model = (DefaultTableModel) hsad123rte.getModel();
        model.setRowCount(0); 
    }//GEN-LAST:event_djskfh123MouseClicked

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel2MouseClicked

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xMouse, y-yMouse);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel dfkjsh12;
    private javax.swing.JTextField djskfh123;
    private javax.swing.JTable hsad123rte;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> sdfjh234nm;
    // End of variables declaration//GEN-END:variables
}
